// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHPfC6NslmJbEo0XV2pNRfCq1epdl-FI',
    appId: '1:660609713234:android:e0ced9c64b4295d2ac0b8b',
    messagingSenderId: '660609713234',
    projectId: 'siri-outarea',
    databaseURL: 'https://siri-outarea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'siri-outarea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55VCyB2VV8TJ2yCaY0XJEQqTln2giARg',
    appId: '1:660609713234:ios:b862b2556133dd03ac0b8b',
    messagingSenderId: '660609713234',
    projectId: 'siri-outarea',
    databaseURL: 'https://siri-outarea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'siri-outarea.appspot.com',
    iosClientId: '660609713234-l4d07t26vgrs4kbluujllia8o06i683v.apps.googleusercontent.com',
    iosBundleId: 'com.getxhomeservice.homeone',
  );
}
